'use client';

import { createContext, useContext, useState, useEffect } from 'react';

type Language = 'ko' | 'vi';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({} as LanguageContextType);

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}

// 번역 데이터
const translations: Record<Language, Record<string, string>> = {
  ko: {
    // 공통
    'common.loading': '로딩 중...',
    'common.login': '로그인',
    'common.logout': '로그아웃',
    'common.signup': '회원가입',
    'common.email': '이메일',
    'common.password': '비밀번호',
    'common.name': '이름',
    'common.submit': '제출',
    'common.cancel': '취소',
    'common.confirm': '확인',
    'common.save': '저장',
    'common.saving': '저장 중...',
    'common.edit': '수정',
    'common.delete': '삭제',
    'common.back': '뒤로',
    'common.next': '다음',
    'common.free': '무료',
    'common.locked': '승인 필요',

    // 로그인 페이지
    'login.title': '로그인',
    'login.subtitle': '베트남 유학생 교육 플랫폼',
    'login.emailPlaceholder': 'your@email.com',
    'login.passwordPlaceholder': '••••••••',
    'login.forgotPassword': '비밀번호 찾기',
    'login.loginWithEmail': '이메일로 로그인',
    'login.loginWithGoogle': '구글로 로그인',
    'login.noAccount': '계정이 없으신가요?',
    'login.or': '또는',
    'login.securityNotice': 'AJU E&J는 계정 공유를 방지하기 위해 한 번에 하나의 기기에서만 로그인이 가능합니다.',
    'login.welcomeBack': 'Welcome Back',
    'login.continueJourney': '학습의 여정을 이어가세요',
    'login.welcomeMessage': 'AJU E&J와 함께하는 체계적인 교육 프로그램으로 목표를 향해 한 걸음씩 나아가세요.',
    'login.loggingIn': '로그인 중...',

    // 비밀번호 찾기
    'resetPassword.title': '비밀번호 찾기',
    'resetPassword.description': '가입한 이메일 주소를 입력하시면 비밀번호 재설정 링크를 보내드립니다.',
    'resetPassword.emailLabel': '이메일 주소',
    'resetPassword.sendLink': '재설정 링크 전송',
    'resetPassword.sending': '전송 중...',
    'resetPassword.successTitle': '이메일 전송 완료',
    'resetPassword.successMessage': '로 비밀번호 재설정 링크를 전송했습니다. 이메일을 확인해주세요.',
    'resetPassword.checkSpam': '이메일이 오지 않았다면 스팸 폴더를 확인해주세요.',

    // 회원가입 페이지
    'signup.title': '회원가입',
    'signup.subtitle': 'AJU E&J 교육 플랫폼에 가입하세요',
    'signup.namePlaceholder': '홍길동',
    'signup.zaloId': 'Zalo ID (선택)',
    'signup.zaloPlaceholder': 'Zalo 아이디',
    'signup.passwordRequirement': '비밀번호는 최소 6자 이상',
    'signup.createAccount': '계정 만들기',
    'signup.hasAccount': '이미 계정이 있으신가요?',
    'signup.creating': '계정 생성 중...',
    'signup.startJourney': '새로운 학습의 시작',
    'signup.joinMessage': 'AJU E&J와 함께 체계적인 교육을 받고, 목표를 향해 나아가세요.',
    'signup.confirmPassword': '비밀번호 확인',
    'signup.confirmPasswordPlaceholder': '비밀번호 재입력',
    'signup.passwordMismatch': '비밀번호가 일치하지 않습니다.',
    'signup.passwordTooShort': '비밀번호는 최소 6자 이상이어야 합니다.',
    'signup.minChars': '최소 6자 이상',
    'signup.zaloHelp': '베트남 거주 시 연락을 위해 사용됩니다',
    'signup.benefit1': '맞춤형 학습 커리큘럼',
    'signup.benefit2': '전문 강사진의 1:1 피드백',
    'signup.benefit3': '언제 어디서나 학습 가능',
    'signup.googleSignup': 'Google로 회원가입',

    // 대시보드
    'dashboard.welcomeBack': 'Welcome Back',
    'dashboard.hello': '안녕하세요',
    'dashboard.startLearning': '오늘도 한국어 학습을 시작해볼까요?',
    'dashboard.myProgress': 'My Progress',
    'dashboard.completed': '완료',
    'dashboard.lessons': 'Lessons',
    'dashboard.lessonList': '강의 목록',
    'dashboard.totalLessons': '총 {count}개 강의',
    'dashboard.noLessons': '아직 등록된 강의가 없습니다.',
    'dashboard.quiz': '퀴즈',
    'dashboard.quizCount': '{count}개',
    'dashboard.completedStatus': '완료됨',
    'dashboard.admin': 'Admin',
    'dashboard.weeklyStudy': '주간 학습',
    'dashboard.completedLessonsLabel': '완료 강의',
    'dashboard.streak': '연속 학습',
    'dashboard.minutes': '분',
    'dashboard.days': '일',
    'dashboard.myCourses': '내 강의',
    'dashboard.featuredCourses': '추천 코스',
    'dashboard.noCourses': '등록된 코스가 없습니다',
    'dashboard.preview': '1강 미리보기',
    'dashboard.enroll': '수강 신청',
    'dashboard.continue': '이어서 학습',
    'dashboard.start': '수강 시작',
    'dashboard.extend': '연장하기',
    'dashboard.expired': '만료됨',
    'dashboard.notStarted': '시작 전',
    'dashboard.expiringWarning': '곧 만료됩니다! 연장해주세요',
    'dashboard.daysLeft': '일 남음',
    'dashboard.lessonsProgress': '강',
    'dashboard.studyDays': '학습한 날',
    'dashboard.consecutiveDays': '연속',
    'dashboard.support': '문의하기',
    'dashboard.supportDesc': '궁금한 점이 있으시면 Zalo로 문의해주세요!',
    'dashboard.contactZalo': 'Zalo 문의',
    'dashboard.studentsEnrolled': '명 수강중',
    'dashboard.delivery': '배송 현황',
    'dashboard.preparing': '준비 중',
    'dashboard.shipped': '배송 중',
    'dashboard.delivered': '배송 완료',
    'dashboard.pending': '처리 대기',
    'dashboard.track': '추적',
    'dashboard.pendingPayment': '입금 대기 중',
    'dashboard.pendingPaymentDesc': '수강 신청이 완료되었습니다.',
    'dashboard.depositAmount': '아래 계좌로 입금해주세요.',
    'dashboard.bankAccount': '입금 계좌',
    'dashboard.accountHolder': '예금주',
    'dashboard.depositConfirm': '입금 완료했습니다',
    'dashboard.confirmSent': '확인 요청 완료',
    'dashboard.detail': '상세보기',
    'dashboard.confirmPending': '관리자가 영업일 기준 1-2일 내에 확인합니다.',
    'dashboard.copiedAccount': '계좌번호가 복사되었습니다.',
    'dashboard.alreadyConfirmed': '이미 입금 확인을 요청했습니다.',
    'dashboard.confirmSuccess': '입금 확인 요청이 전송되었습니다!',
    'dashboard.enrollmentComplete': '수강 신청이 완료되었습니다.',
    'dashboard.pleaseDeposit': '아래 계좌로 입금해주세요.',
    'dashboard.won': '원',
    'dashboard.depositAccount': '입금 계좌',
    'dashboard.confirmRequestComplete': '확인 요청 완료',
    'dashboard.viewDetails': '상세보기',
    'dashboard.adminWillConfirm': '관리자가 영업일 기준 1-2일 내에 확인합니다.',
    'dashboard.accountCopied': '계좌번호가 복사되었습니다.',
    'dashboard.alreadyRequested': '이미 입금 확인을 요청했습니다.',
    'dashboard.depositRequestSent': '입금 확인 요청이 전송되었습니다!',
    'dashboard.requestFailed': '요청에 실패했습니다.',

    // 결제 대기
    'payment.waiting': '결제 대기 중',
    'payment.waitingMessage': '강의를 시청하려면 관리자의 승인이 필요합니다. Zalo로 문의해주세요.',
    'payment.contactZalo': 'Zalo 문의하기',
    'payment.paymentGuide': '결제 가이드',
    'payment.needPermission': '수강 권한이 필요합니다. 관리자 승인을 기다려주세요.',
    'payment.firstFree': '(1강은 무료로 시청 가능합니다)',

    // 코스
    'course.list': '코스 목록',
    'course.detail': '코스 상세',
    'course.chapters': '강의 목차',
    'course.chaptersCount': '{count}개',
    'course.noChapters': '등록된 강의가 없습니다.',
    'course.duration': '{duration}분',

    // 학습 가이드
    'guide.title': 'AJU E&J 학습 가이드',
    'guide.tip1': '각 강의를 순서대로 수강하는 것을 권장합니다',
    'guide.tip2': '강의 시청 후 퀴즈를 풀어 학습 내용을 확인하세요',
    'guide.tip3': '모든 학습 기록은 자동으로 저장됩니다',
    'guide.tip4': '문의사항은 admin@ajuenj.com으로 연락주세요',

    // 강의 시청
    'learn.backToDashboard': '대시보드로 돌아가기',
    'learn.lesson': 'Lesson',
    'learn.lessonNotFound': '강의를 찾을 수 없습니다.',
    'learn.quiz': '학습 확인 퀴즈',
    'learn.quizDescription': '강의 내용을 잘 이해했는지 확인해보세요',
    'learn.question': '문제',
    'learn.submitQuiz': '퀴즈 제출하기',
    'learn.quizComplete': '퀴즈 완료!',
    'learn.score': '점',
    'learn.excellent': '훌륭합니다! 다음 강의로 진행하세요.',
    'learn.good': '좋습니다! 복습하면 더 좋을 것 같아요.',
    'learn.tryAgain': '다시 한번 강의를 시청해보세요.',
    'learn.explanation': '해설',
    'learn.answerAll': '모든 문제에 답해주세요.',
    'learn.growWithUs': 'AJU E&J와 함께 성장하세요! 모든 학습 기록은 자동 저장됩니다.',

    // 푸터
    'footer.copyright': '© 2026 AJU E&J. All rights reserved.',
    'footer.disclaimer': '본 사이트의 모든 콘텐츠(영상, 텍스트, 이미지 등)는 AJU E&J의 자산으로서 저작권법에 의해 보호됩니다. 무단 복제, 배포, 전송을 금지합니다.',

    // 랜딩 페이지
    'landing.heroTitle1': '배움의 새로운',
    'landing.heroTitle2': '여정을 시작하세요',
    'landing.heroSubtitle': 'AJU E&J와 함께하는 베트남 유학생 전문 교육 플랫폼. 한국어 실력 향상과 성공적인 한국 생활을 위한 맞춤형 학습을 경험하세요.',
    'landing.startFree': '무료로 시작하기',
    'landing.existingMember': '기존 회원 로그인',
    'landing.getStarted': '시작하기',
    'landing.whyChooseUs': '학습의 모든 것',
    'landing.secureContent': '안전한 콘텐츠 보호',
    'landing.secureContentDesc': '계정 공유 방지 시스템으로 프리미엄 교육 콘텐츠를 안전하게 보호합니다. 한 기기에서만 접속 가능한 보안 시스템을 적용했습니다.',
    'landing.mobileOptimized': '모바일 최적화',
    'landing.personalizedEducation': '맞춤형 교육',
    'landing.systematicCurriculum': '체계적인 커리큘럼',
    'landing.systematicCurriculumDesc': '베트남 유학생의 니즈에 맞춘 전문 커리큘럼으로 효과적인 학습을 지원합니다. 한국어부터 생활 정보까지 필요한 모든 것을 제공합니다.',

    // 관리자
    'admin.dashboard': '관리자 대시보드',
    'admin.description': '학생 관리 및 강의 콘텐츠를 한눈에 확인하세요',
    'admin.totalStudents': '전체 학생',
    'admin.pending': '대기 중',
    'admin.approved': '승인됨',
    'admin.studentManagement': '학생 관리',
    'admin.contentManagement': '강의 관리',
    'admin.studentList': '학생 목록',
    'admin.studentListDesc': '등록된 학생들의 정보와 수강 권한을 관리합니다',
    'admin.noStudents': '아직 등록된 학생이 없습니다.',
    'admin.zaloId': 'Zalo ID',
    'admin.location': '거주지',
    'admin.level': '레벨',
    'admin.status': '상태',
    'admin.action': '액션',
    'admin.canWatch': '수강 가능',
    'admin.revokePermission': '권한 취소',
    'admin.grantPermission': '권한 부여',
    'admin.contentManagementTitle': '강의 콘텐츠 관리',
    'admin.contentManagementDesc': '강의 영상과 퀴즈를 추가, 수정, 삭제합니다',
    'admin.addNewLesson': '새 강의 추가',
    'admin.noLessonsAdmin': '등록된 강의가 없습니다.',
    'admin.courseManagement': '코스 관리',
    'admin.courseManagementDesc': '코스 추가 및 수정',
    'admin.gradeManagement': '성적 관리',
    'admin.gradeManagementDesc': '학생 성적 확인',
    'admin.studentView': '학생 화면',
    'admin.beginner': '초급',
    'admin.intermediate': '중급',
    'admin.advanced': '고급',
    'admin.confirmRevoke': '정말로 이 학생의 승인을 취소하시겠습니까?',
    'admin.confirmGrant': '이 학생에게 수강 권한을 부여하시겠습니까?',
    'admin.updateFailed': '권한 업데이트에 실패했습니다.',
    'admin.lesson': '강의',
    'admin.edit': '수정',
    'admin.viewAllStudents': '전체 학생 보기',

    // 코스 페이지
    'courses.title': '강의 목록',
    'courses.subtitle': 'AJU E&J가 제공하는 베트남 유학생 전용 교육 콘텐츠',
    'courses.waitingApproval': '수강 권한 대기 중',
    'courses.waitingMessage': '관리자의 승인을 기다리고 있습니다. 승인 후 모든 강의를 시청할 수 있습니다.',
    'courses.contact': '문의: admin@ajuenj.com',
    'courses.loadingCourses': '강의를 불러오는 중...',
    'courses.noCourses': '등록된 강의가 없습니다.',
    'courses.startCourse': '강의 시작하기',
    'courses.waitingStatus': '승인 대기 중',
    'courses.brandTitle': 'AJU E&J Education',
    'courses.brandDesc': '베트남 유학생의 성공적인 한국 생활을 위한 맞춤형 교육 프로그램',
    'courses.feature1': '체계적인 커리큘럼',
    'courses.feature2': '실무 중심 교육',
    'courses.feature3': '언제 어디서나 학습',

    // 내 학습 진도
    'progress.title': '내 학습 현황',
    'progress.subtitle': '학습 현황을 확인하세요',
    'progress.overall': '전체 진도율',
    'progress.completedLessons': '완료한 강의',
    'progress.totalLessons': '전체 강의',
    'progress.quizAverage': '퀴즈 평균 점수',
    'progress.recentActivity': '최근 학습 활동',
    'progress.noActivity': '아직 학습 기록이 없습니다.',
    'progress.startLearning': '지금 바로 학습을 시작하세요!',
    'progress.goToDashboard': '대시보드로 이동',
    'progress.lessonCompleted': '강의 완료',
    'progress.quizScore': '퀴즈 점수',
    'progress.submittedQuizzes': '제출한 퀴즈',
    'progress.averageScore': '평균 점수',
    'progress.count': '개',
    'progress.points': '점',
    'progress.progressByCourse': '코스별 진도',
    'progress.noCourses': '등록된 코스가 없습니다.',
    'progress.completed': '완료',
    'progress.progressRate': '진도율',
    'progress.recentQuizResults': '최근 퀴즈 결과',
    'progress.noQuizzes': '아직 제출한 퀴즈가 없습니다.',
    'progress.chapter': '챕터',
    'progress.score': '점수',
    'progress.submittedDate': '제출일',
    'progress.unknown': '알 수 없음',

    // 프로필 설정
    'profile.title': '프로필 설정',
    'profile.subtitle': '학습에 필요한 정보를 입력해주세요',
    'profile.name': '이름',
    'profile.namePlaceholder': '예: NGUYEN VAN A',
    'profile.zaloId': 'Zalo ID',
    'profile.zaloPlaceholder': '예: zalo123456',
    'profile.location': '거주 지역',
    'profile.locationPlaceholder': '현재 거주 지역',
    'profile.level': '한국어 레벨',
    'profile.selectLevel': '선택하세요',
    'profile.saveProfile': '프로필 저장',
    'profile.saving': '저장 중...',
    'profile.welcome': '환영합니다!',
    'profile.welcomeMessage': '학습을 시작하기 전에 프로필을 설정해주세요',
    'profile.nameRequired': '이름은 필수 입력 항목입니다.',
    'profile.passportName': '여권 성함',
    'profile.optional': '선택',
    'profile.zaloHelp': '학습 관련 공지사항을 받으실 수 있습니다',
    'profile.startLearning': '학습 시작하기',
    'profile.skip': '건너뛰기',
    'profile.privacyNotice': '입력하신 정보는 AJU E&J 교육 서비스 제공을 위해서만 사용됩니다',

    // 네비게이션
    'nav.dashboard': '대시보드',
    'nav.courses': '강의',
    'nav.myProgress': '학습 진도',
    'nav.myOrders': '주문 내역',
    'nav.admin': '관리자',

    // 학생 레이아웃
    'layout.menu': '메뉴',
    'layout.closeMenu': '메뉴 닫기',

    // 챕터 관리
    'chapters.title': '챕터 관리',
    'chapters.description': '강의 챕터를 추가하고 관리합니다',
    'chapters.addNew': '새 챕터 추가',
    'chapters.editChapter': '챕터 수정',
    'chapters.courseFilter': '코스 필터',
    'chapters.allCourses': '전체 코스',
    'chapters.selectCourse': '코스 선택',
    'chapters.chapterTitle': '챕터 제목',
    'chapters.titlePlaceholder': '챕터 제목을 입력하세요',
    'chapters.youtubeUrl': 'YouTube URL',
    'chapters.youtubeHelp': 'YouTube 공유 링크를 입력하세요 (예: https://youtu.be/...)',
    'chapters.sortOrder': '정렬 순서',
    'chapters.videoDuration': '영상 길이 (분)',
    'chapters.durationPlaceholder': '분',
    'chapters.quizSettings': '퀴즈 설정',
    'chapters.optional': '선택',
    'chapters.questions': '개 문제',
    'chapters.question': '문제',
    'chapters.questionPlaceholder': '문제를 입력하세요',
    'chapters.option': '선택지',
    'chapters.correct': '정답',
    'chapters.incorrectOptions': '오답 선택지',
    'chapters.explanation': '해설',
    'chapters.explanationPlaceholder': '해설을 입력하세요 (선택)',
    'chapters.removeQuestion': '문제 삭제',
    'chapters.addQuestion': '문제 추가',
    'chapters.updated': '챕터가 수정되었습니다.',
    'chapters.added': '챕터가 추가되었습니다.',
    'chapters.confirmDelete': '정말로 이 챕터를 삭제하시겠습니까?',
    'chapters.deleted': '챕터가 삭제되었습니다.',
    'chapters.deleteFailed': '챕터 삭제에 실패했습니다.',
    'chapters.saveFailed': '저장에 실패했습니다.',
    'chapters.chaptersCount': '개 챕터',
    'chapters.order': '순서',
    'chapters.chapterInfo': '챕터 정보',
    'chapters.course': '코스',
    'chapters.quiz': '퀴즈',
    'chapters.actions': '작업',
    'chapters.noChapters': '등록된 챕터가 없습니다.',
    'chapters.minutes': '분',
    'chapters.noTime': '시간 없음',
    'chapters.noCourse': '코스 없음',
    'chapters.none': '없음',
    'chapters.helpGuide': '챕터 관리 가이드',
    'chapters.helpTip1': 'YouTube URL은 공유 링크 형식으로 입력하세요',
    'chapters.helpTip2': '정렬 순서가 낮을수록 먼저 표시됩니다',
    'chapters.helpTip3': '퀴즈는 선택사항이며, 학습 확인용으로 사용됩니다',
    'chapters.helpTip4': '챕터 삭제 시 해당 퀴즈 기록도 함께 삭제됩니다',

    // 코스 관리
    'courses.managementTitle': '코스 관리',
    'courses.managementDesc': '코스를 추가하고 관리합니다',
    'courses.addNew': '새 코스 추가',
    'courses.editCourse': '코스 수정',
    'courses.courseTitle': '코스 제목',
    'courses.titlePlaceholder': '코스 제목을 입력하세요',
    'courses.courseDescription': '코스 설명',
    'courses.descriptionPlaceholder': '코스 설명을 입력하세요',
    'courses.thumbnailUrl': '썸네일 URL',
    'courses.sortOrder': '정렬 순서',
    'courses.activeStatus': '활성화 상태',
    'courses.active': '활성',
    'courses.inactive': '비활성',
    'courses.add': '추가',
    'courses.courseUpdated': '코스가 수정되었습니다.',
    'courses.courseAdded': '코스가 추가되었습니다.',
    'courses.saveFailed': '저장에 실패했습니다.',
    'courses.confirmDelete': '정말로 이 코스를 삭제하시겠습니까?',
    'courses.courseDeleted': '코스가 삭제되었습니다.',
    'courses.deleteFailed': '코스 삭제에 실패했습니다.',
    'courses.coursesCount': '개 코스',
    'courses.order': '순서',
    'courses.courseInfo': '코스 정보',

    // 성적 관리
    'grades.title': '성적 관리',
    'grades.description': '학생들의 퀴즈 성적을 확인합니다',
    'grades.courseFilter': '코스 필터',
    'grades.allCourses': '전체 코스',
    'grades.totalStudents': '전체 학생',
    'grades.submittedQuizzes': '제출된 퀴즈',
    'grades.overallAverage': '전체 평균',
    'grades.highestScore': '최고 점수',
    'grades.studentGrades': '학생별 성적',
    'grades.rank': '순위',
    'grades.studentInfo': '학생 정보',
    'grades.submissions': '제출 수',
    'grades.averageScore': '평균 점수',
    'grades.noData': '데이터가 없습니다.',
    'grades.submissionsCount': '개',
    'grades.points': '점',
    'grades.excellent': '우수',
    'grades.average': '보통',
    'grades.needsWork': '노력 필요',
    'grades.chapterQuizStats': '챕터별 퀴즈 정답률',
    'grades.takers': '명 응시',

    // 학생 관리
    'students.title': '학생 관리',
    'students.description': '가입한 학생의 결제를 확인하고 수강 권한을 승인합니다',
    'students.total': '전체',
    'students.pending': '대기 중',
    'students.approved': '승인됨',
    'students.studentInfo': '학생 정보',
    'students.contact': '연락처',
    'students.locationLevel': '지역/레벨',
    'students.joinDate': '가입일',
    'students.noStudents': '학생이 없습니다',
    'students.notRegistered': '미등록',
    'students.notSet': '미설정',
    'students.beginner': '초급',
    'students.intermediate': '중급',
    'students.advanced': '고급',
    'students.revoke': '취소',
    'students.approve': '승인',
    'students.confirmRevoke': '정말로 이 학생의 승인을 취소하시겠습니까?',
    'students.confirmApprove': '이 학생에게 수강 권한을 부여하시겠습니까?',
    'students.approvalRevoked': '승인이 취소되었습니다',
    'students.approvalError': '승인 처리 중 오류가 발생했습니다.',
    'students.approvalGuide': '승인 가이드',
    'students.guideTip1': 'Zalo ID를 확인하여 실제 수강생인지 확인하세요',
    'students.guideTip2': '입금이 확인된 학생만 승인 버튼을 눌러주세요',
    'students.guideTip3': '승인된 학생만 강의 콘텐츠에 접근할 수 있습니다',
    'students.searchPlaceholder': '이름 또는 이메일로 검색...',

    // 관리자 네비게이션
    'adminNav.adminPanel': '관리자 패널',
    'adminNav.navigation': '메뉴',
    'adminNav.dashboard': '대시보드',
    'adminNav.dashboardSub': '대시보드',
    'adminNav.orders': '주문 및 배송 관리',
    'adminNav.ordersSub': '주문/배송',
    'adminNav.students': '학생 관리',
    'adminNav.studentsSub': '학생',
    'adminNav.courses': '코스 관리',
    'adminNav.coursesSub': '코스',
    'adminNav.chaptersSimple': '챕터 관리 (간편)',
    'adminNav.chaptersSub': '챕터',
    'adminNav.chaptersDetail': '챕터 관리 (상세)',
    'adminNav.chaptersDetailSub': '챕터 상세',
    'adminNav.grades': '성적 조회',
    'adminNav.gradesSub': '성적',
    'adminNav.studentView': '학생 화면',

    // 구독 관리
    'subscription.status': '구독 상태',
    'subscription.period': '구독 기간',
    'subscription.active': '구독 중',
    'subscription.expired': '만료됨',
    'subscription.unlimited': '무제한',
    'subscription.approve': '승인',
    'subscription.extend': '연장',
    'subscription.renew': '갱신',
    'subscription.revoke': '취소',
    'subscription.approved': '✅ 구독이 승인되었습니다.',
    'subscription.extended': '✅ 구독이 연장되었습니다.',
    'subscription.error': '구독 처리 중 오류가 발생했습니다.',
    'subscription.approveTitle': '구독 승인',
    'subscription.extendTitle': '구독 연장',
    'subscription.selectPeriod': '구독 기간 선택',
    'subscription.customInput': '직접 입력',
    'subscription.month': '개월',
    'subscription.months': '개월',
    'subscription.monthPlan': '개월 플랜',
    'subscription.currentExpiry': '현재 만료일',
    'subscription.newExpiry': '연장 후 만료일',
    'subscription.expiryDate': '만료 예정일',
    'subscription.daysRemaining': '{days}일 남음',
    'subscription.until': '까지',
    'subscription.expiredMessage': '구독 기간이 만료되었습니다. 계속 학습하시려면 구독을 갱신해주세요.',
    'subscription.expiringMessage': '구독이 {days}일 후에 만료됩니다. Zalo로 연락하여 갱신해주세요.',
    'subscription.guide': '구독 관리 가이드',
    'subscription.guideTip1': '1개월, 3개월, 6개월, 12개월 단위로 구독 기간을 설정할 수 있습니다',
    'subscription.guideTip2': '구독 연장 시 기존 만료일에서 추가됩니다 (만료된 경우 오늘부터)',
    'subscription.guideTip3': '만료 7일 전부터 빨간색으로 표시됩니다',
    'subscription.guideTip4': '만료된 학생은 강의 접근이 자동으로 차단됩니다',

    // 챕터 관리 V2 (간편 모드)
    'chaptersV2.title': '챕터 관리 (간편 모드)',
    'chaptersV2.description': '코스별 챕터를 간편하게 추가하고 관리합니다',
    'chaptersV2.step1Title': '코스 선택 (교과서 폴더)',
    'chaptersV2.noCourses': '등록된 코스가 없습니다.',
    'chaptersV2.goAddCourse': '코스 추가하러 가기 →',
    'chaptersV2.chaptersCount': '개 챕터',
    'chaptersV2.chapterList': '챕터 목록',
    'chaptersV2.addChapter': '챕터 추가',
    'chaptersV2.noChaptersYet': '아직 챕터가 없습니다',
    'chaptersV2.clickAddChapter': '위의 "챕터 추가" 버튼을 클릭하세요',
    'chaptersV2.quizQuestions': '{count}개 퀴즈',
    'chaptersV2.editChapter': '챕터 수정',
    'chaptersV2.addNewChapter': '새 챕터 추가',
    'chaptersV2.chapterTitle': '챕터 제목',
    'chaptersV2.titlePlaceholder': '예: 1강 - 한국어 기초',
    'chaptersV2.youtubeUrl': 'YouTube URL',
    'chaptersV2.youtubeHelp': 'YouTube 동영상 URL을 입력하세요',
    'chaptersV2.order': '순서',
    'chaptersV2.videoDuration': '영상 길이 (분)',
    'chaptersV2.quizOptional': '퀴즈 (선택사항)',
    'chaptersV2.addQuestion': '문제 추가',
    'chaptersV2.question': '문제',
    'chaptersV2.option': '선택지',
    'chaptersV2.deleteQuestion': '문제 삭제',
    'chaptersV2.update': '수정',
    'chaptersV2.add': '추가',
    'chaptersV2.helpTitle': '💡 사용 가이드',
    'chaptersV2.helpTip1': '먼저 코스를 선택하세요',
    'chaptersV2.helpTip2': '챕터 제목과 YouTube URL은 필수입니다',
    'chaptersV2.helpTip3': '퀴즈는 선택사항입니다',
    'chaptersV2.helpTip4': '순서 번호가 낮을수록 먼저 표시됩니다',
    'chaptersV2.selectCourseAlert': '코스를 선택해주세요.',
    'chaptersV2.requiredFieldsAlert': '챕터 제목과 YouTube URL은 필수입니다.',
    'chaptersV2.chapterUpdated': '✅ 챕터가 수정되었습니다.',
    'chaptersV2.chapterAdded': '✅ 챕터가 추가되었습니다.',
    'chaptersV2.saveError': '저장 중 오류가 발생했습니다.',
    'chaptersV2.chapterDeleted': '✅ 챕터가 삭제되었습니다.',
    'chaptersV2.deleteError': '삭제 중 오류가 발생했습니다.',

    // 알림
    'notification.title': '알림',
    'notification.markAllRead': '모두 읽음',
    'notification.loading': '로딩 중...',
    'notification.noNotifications': '알림이 없습니다',
    'notification.justNow': '방금 전',
    'notification.minutesAgo': '{n}분 전',
    'notification.hoursAgo': '{n}시간 전',
    'notification.daysAgo': '{n}일 전',
    'notification.showingRecent': '최근 {n}개 알림 표시 중',

    // 주문 내역
    'orders.title': '주문 내역',
    'orders.subtitle': '나의 수강 신청 및 결제 내역을 확인하세요',
    'orders.noOrders': '주문 내역이 없습니다',
    'orders.goEnroll': '코스 둘러보기',
    'orders.orderDate': '주문일',
    'orders.orderId': '주문번호',
    'orders.courseName': '코스명',
    'orders.period': '수강 기간',
    'orders.months': '개월',
    'orders.amount': '결제 금액',
    'orders.courseAmount': '강의 금액',
    'orders.textbookAmount': '교재 금액',
    'orders.totalAmount': '총 결제 금액',
    'orders.status': '주문 상태',
    'orders.pendingPayment': '입금 대기',
    'orders.paid': '결제 완료',
    'orders.cancelled': '취소됨',
    'orders.depositInfo': '입금 안내',
    'orders.bankName': '은행명',
    'orders.accountNumber': '계좌번호',
    'orders.accountHolder': '예금주',
    'orders.copyAccount': '복사',
    'orders.copied': '복사됨!',
    'orders.confirmDeposit': '입금 완료 알림',
    'orders.depositConfirmed': '입금 확인 요청 완료',
    'orders.waitingConfirm': '관리자 확인 중',
    'orders.deliveryInfo': '배송 정보',
    'orders.deliveryStatus': '배송 상태',
    'orders.trackingNumber': '운송장 번호',
    'orders.carrier': '택배사',
    'orders.preparing': '배송 준비 중',
    'orders.shipped': '배송 중',
    'orders.delivered': '배송 완료',
    'orders.trackDelivery': '배송 조회',
    'orders.shippingAddress': '배송지',
    'orders.recipient': '수취인',
    'orders.phone': '연락처',
    'orders.address': '주소',
    'orders.textbook': '교재',
    'orders.included': '포함',
    'orders.notIncluded': '미포함',
    'orders.won': '원',
  },
  vi: {
    // 공통
    'common.loading': 'Đang tải...',
    'common.login': 'Đăng nhập',
    'common.logout': 'Đăng xuất',
    'common.signup': 'Đăng ký',
    'common.email': 'Email',
    'common.password': 'Mật khẩu',
    'common.name': 'Tên',
    'common.submit': 'Gửi',
    'common.cancel': 'Hủy',
    'common.confirm': 'Xác nhận',
    'common.save': 'Lưu',
    'common.saving': 'Đang lưu...',
    'common.edit': 'Sửa',
    'common.delete': 'Xóa',
    'common.back': 'Quay lại',
    'common.next': 'Tiếp theo',
    'common.free': 'Miễn phí',
    'common.locked': 'Cần phê duyệt',

    // 로그인 페이지
    'login.title': 'Đăng nhập',
    'login.subtitle': 'Nền tảng giáo dục cho du học sinh Việt Nam',
    'login.emailPlaceholder': 'your@email.com',
    'login.passwordPlaceholder': '••••••••',
    'login.forgotPassword': 'Quên mật khẩu',
    'login.loginWithEmail': 'Đăng nhập bằng Email',
    'login.loginWithGoogle': 'Đăng nhập bằng Google',
    'login.noAccount': 'Chưa có tài khoản?',
    'login.or': 'hoặc',
    'login.securityNotice': 'AJU E&J chỉ cho phép đăng nhập trên một thiết bị tại một thời điểm để ngăn chặn việc chia sẻ tài khoản.',
    'login.welcomeBack': 'Welcome Back',
    'login.continueJourney': 'Tiếp tục hành trình học tập của bạn',
    'login.welcomeMessage': 'Cùng AJU E&J tiến từng bước đến mục tiêu với chương trình giáo dục có hệ thống.',
    'login.loggingIn': 'Đang đăng nhập...',

    // 비밀번호 찾기
    'resetPassword.title': 'Quên mật khẩu',
    'resetPassword.description': 'Nhập địa chỉ email đã đăng ký, chúng tôi sẽ gửi link đặt lại mật khẩu.',
    'resetPassword.emailLabel': 'Địa chỉ Email',
    'resetPassword.sendLink': 'Gửi link đặt lại',
    'resetPassword.sending': 'Đang gửi...',
    'resetPassword.successTitle': 'Đã gửi Email',
    'resetPassword.successMessage': 'Đã gửi link đặt lại mật khẩu đến. Vui lòng kiểm tra email.',
    'resetPassword.checkSpam': 'Nếu không nhận được email, vui lòng kiểm tra thư mục spam.',

    // 회원가입 페이지
    'signup.title': 'Đăng ký',
    'signup.subtitle': 'Tham gia nền tảng giáo dục AJU E&J',
    'signup.namePlaceholder': 'Nguyễn Văn A',
    'signup.zaloId': 'Zalo ID (tùy chọn)',
    'signup.zaloPlaceholder': 'ID Zalo',
    'signup.passwordRequirement': 'Mật khẩu tối thiểu 6 ký tự',
    'signup.createAccount': 'Tạo tài khoản',
    'signup.hasAccount': 'Đã có tài khoản?',
    'signup.creating': 'Đang tạo tài khoản...',
    'signup.startJourney': 'Bắt đầu hành trình học tập mới',
    'signup.joinMessage': 'Cùng AJU E&J nhận được sự giáo dục có hệ thống và tiến đến mục tiêu của bạn.',
    'signup.confirmPassword': 'Xác nhận mật khẩu',
    'signup.confirmPasswordPlaceholder': 'Nhập lại mật khẩu',
    'signup.passwordMismatch': 'Mật khẩu không khớp.',
    'signup.passwordTooShort': 'Mật khẩu phải có ít nhất 6 ký tự.',
    'signup.minChars': 'Tối thiểu 6 ký tự',
    'signup.zaloHelp': 'Dùng để liên lạc khi ở Việt Nam',
    'signup.benefit1': 'Chương trình học tùy chỉnh',
    'signup.benefit2': 'Phản hồi 1:1 từ giảng viên chuyên nghiệp',
    'signup.benefit3': 'Học mọi lúc, mọi nơi',
    'signup.googleSignup': 'Đăng ký bằng Google',

    // 대시보드
    'dashboard.welcomeBack': 'Welcome Back',
    'dashboard.hello': 'Xin chào',
    'dashboard.startLearning': 'Hôm nay cũng bắt đầu học tiếng Hàn nhé?',
    'dashboard.myProgress': 'My Progress',
    'dashboard.completed': 'hoàn thành',
    'dashboard.lessons': 'Lessons',
    'dashboard.lessonList': 'Danh sách bài học',
    'dashboard.totalLessons': 'Tổng {count} bài học',
    'dashboard.noLessons': 'Chưa có bài học nào được đăng ký.',
    'dashboard.quiz': 'Quiz',
    'dashboard.quizCount': '{count} câu',
    'dashboard.completedStatus': 'Đã hoàn thành',
    'dashboard.admin': 'Admin',
    'dashboard.weeklyStudy': 'Học tuần này',
    'dashboard.completedLessonsLabel': 'Đã hoàn thành',
    'dashboard.streak': 'Liên tục',
    'dashboard.minutes': 'phút',
    'dashboard.days': 'ngày',
    'dashboard.myCourses': 'Khóa học của tôi',
    'dashboard.featuredCourses': 'Khóa học đề xuất',
    'dashboard.noCourses': 'Chưa có khóa học',
    'dashboard.preview': 'Xem trước bài 1',
    'dashboard.enroll': 'Đăng ký học',
    'dashboard.continue': 'Tiếp tục học',
    'dashboard.start': 'Bắt đầu học',
    'dashboard.extend': 'Gia hạn',
    'dashboard.expired': 'Đã hết hạn',
    'dashboard.notStarted': 'Chưa bắt đầu',
    'dashboard.expiringWarning': 'Sắp hết hạn! Gia hạn ngay',
    'dashboard.daysLeft': 'ngày còn lại',
    'dashboard.lessonsProgress': 'bài',
    'dashboard.studyDays': 'Ngày học',
    'dashboard.consecutiveDays': 'Liên tục',
    'dashboard.support': 'Hỗ trợ',
    'dashboard.supportDesc': 'Nếu bạn có câu hỏi, hãy liên hệ qua Zalo!',
    'dashboard.contactZalo': 'Liên hệ Zalo',
    'dashboard.studentsEnrolled': ' học viên',
    'dashboard.delivery': 'Tình trạng giao hàng',
    'dashboard.preparing': 'Đang chuẩn bị',
    'dashboard.shipped': 'Đang giao',
    'dashboard.delivered': 'Đã giao',
    'dashboard.pending': 'Chờ xử lý',
    'dashboard.track': 'Theo dõi',
    'dashboard.pendingPayment': 'Đang chờ thanh toán',
    'dashboard.pendingPaymentDesc': 'Đăng ký học đã hoàn tất.',
    'dashboard.depositAmount': 'Vui lòng chuyển khoản vào tài khoản dưới đây.',
    'dashboard.bankAccount': 'Tài khoản',
    'dashboard.accountHolder': 'Chủ TK',
    'dashboard.depositConfirm': 'Tôi đã chuyển khoản',
    'dashboard.confirmSent': 'Đã gửi yêu cầu',
    'dashboard.detail': 'Chi tiết',
    'dashboard.confirmPending': 'Quản trị viên sẽ xác nhận trong 1-2 ngày làm việc.',
    'dashboard.copiedAccount': 'Đã sao chép số tài khoản.',
    'dashboard.alreadyConfirmed': 'Đã gửi yêu cầu xác nhận rồi.',
    'dashboard.confirmSuccess': 'Đã gửi yêu cầu xác nhận thanh toán!',
    'dashboard.enrollmentComplete': 'Đăng ký học đã hoàn tất.',
    'dashboard.pleaseDeposit': 'Vui lòng chuyển khoản vào tài khoản dưới đây.',
    'dashboard.won': 'won',
    'dashboard.depositAccount': 'Tài khoản',
    'dashboard.confirmRequestComplete': 'Đã gửi yêu cầu',
    'dashboard.viewDetails': 'Chi tiết',
    'dashboard.adminWillConfirm': 'Quản trị viên sẽ xác nhận trong 1-2 ngày làm việc.',
    'dashboard.accountCopied': 'Đã sao chép số tài khoản.',
    'dashboard.alreadyRequested': 'Đã gửi yêu cầu xác nhận rồi.',
    'dashboard.depositRequestSent': 'Đã gửi yêu cầu xác nhận thanh toán!',
    'dashboard.requestFailed': 'Yêu cầu thất bại.',

    // 결제 대기
    'payment.waiting': 'Đang chờ thanh toán',
    'payment.waitingMessage': 'Cần sự phê duyệt của quản trị viên để xem bài giảng. Vui lòng liên hệ qua Zalo.',
    'payment.contactZalo': 'Liên hệ Zalo',
    'payment.paymentGuide': 'Hướng dẫn thanh toán',
    'payment.needPermission': 'Cần quyền học. Vui lòng đợi phê duyệt từ quản trị viên.',
    'payment.firstFree': '(Bài 1 có thể xem miễn phí)',

    // 코스
    'course.list': 'Danh sách khóa học',
    'course.detail': 'Chi tiết khóa học',
    'course.chapters': 'Mục lục bài học',
    'course.chaptersCount': '{count} bài',
    'course.noChapters': 'Chưa có bài giảng nào.',
    'course.duration': '{duration} phút',

    // 학습 가이드
    'guide.title': 'Hướng dẫn học AJU E&J',
    'guide.tip1': 'Khuyến nghị học các bài theo thứ tự',
    'guide.tip2': 'Sau khi xem bài giảng, hãy làm quiz để kiểm tra',
    'guide.tip3': 'Tất cả tiến độ học tập được lưu tự động',
    'guide.tip4': 'Mọi thắc mắc xin liên hệ admin@ajuenj.com',

    // 강의 시청
    'learn.backToDashboard': 'Quay lại Dashboard',
    'learn.lesson': 'Lesson',
    'learn.lessonNotFound': 'Không tìm thấy bài học.',
    'learn.quiz': 'Quiz kiểm tra',
    'learn.quizDescription': 'Kiểm tra xem bạn đã hiểu nội dung bài học chưa',
    'learn.question': 'Câu hỏi',
    'learn.submitQuiz': 'Nộp Quiz',
    'learn.quizComplete': 'Hoàn thành Quiz!',
    'learn.score': 'điểm',
    'learn.excellent': 'Xuất sắc! Tiếp tục bài tiếp theo.',
    'learn.good': 'Tốt! Ôn lại sẽ tốt hơn.',
    'learn.tryAgain': 'Hãy xem lại bài giảng một lần nữa.',
    'learn.explanation': 'Giải thích',
    'learn.answerAll': 'Vui lòng trả lời tất cả câu hỏi.',
    'learn.growWithUs': 'Cùng AJU E&J phát triển! Tất cả tiến độ được lưu tự động.',

    // 푸터
    'footer.copyright': '© 2026 AJU E&J. All rights reserved.',
    'footer.disclaimer': 'Tất cả nội dung trên trang web này (video, văn bản, hình ảnh, v.v.) là tài sản của AJU E&J và được bảo vệ bởi luật bản quyền. Nghiêm cấm sao chép, phân phối, truyền tải trái phép.',

    // 랜딩 페이지
    'landing.heroTitle1': 'Hành trình học tập',
    'landing.heroTitle2': 'mới bắt đầu',
    'landing.heroSubtitle': 'Nền tảng giáo dục chuyên nghiệp cho du học sinh Việt Nam cùng AJU E&J. Trải nghiệm học tập tùy chỉnh để nâng cao tiếng Hàn và cuộc sống thành công tại Hàn Quốc.',
    'landing.startFree': 'Bắt đầu miễn phí',
    'landing.existingMember': 'Đăng nhập thành viên',
    'landing.getStarted': 'Bắt đầu',
    'landing.whyChooseUs': 'Tất cả về học tập',
    'landing.secureContent': 'Bảo vệ nội dung an toàn',
    'landing.secureContentDesc': 'Bảo vệ nội dung giáo dục cao cấp an toàn với hệ thống chống chia sẻ tài khoản. Áp dụng hệ thống bảo mật chỉ cho phép truy cập từ một thiết bị.',
    'landing.mobileOptimized': 'Tối ưu hóa di động',
    'landing.personalizedEducation': 'Giáo dục tùy chỉnh',
    'landing.systematicCurriculum': 'Chương trình có hệ thống',
    'landing.systematicCurriculumDesc': 'Hỗ trợ học tập hiệu quả với chương trình giảng dạy chuyên nghiệp phù hợp với nhu cầu của du học sinh Việt Nam. Cung cấp mọi thứ cần thiết từ tiếng Hàn đến thông tin cuộc sống.',

    // 관리자
    'admin.dashboard': 'Bảng điều khiển Admin',
    'admin.description': 'Quản lý học sinh và nội dung bài giảng',
    'admin.totalStudents': 'Tổng học sinh',
    'admin.pending': 'Đang chờ',
    'admin.approved': 'Đã duyệt',
    'admin.studentManagement': 'Quản lý học sinh',
    'admin.contentManagement': 'Quản lý bài giảng',
    'admin.studentList': 'Danh sách học sinh',
    'admin.studentListDesc': 'Quản lý thông tin và quyền học của học sinh đã đăng ký',
    'admin.noStudents': 'Chưa có học sinh nào đăng ký.',
    'admin.zaloId': 'Zalo ID',
    'admin.location': 'Nơi ở',
    'admin.level': 'Trình độ',
    'admin.status': 'Trạng thái',
    'admin.action': 'Hành động',
    'admin.canWatch': 'Có thể học',
    'admin.revokePermission': 'Thu hồi quyền',
    'admin.grantPermission': 'Cấp quyền',
    'admin.contentManagementTitle': 'Quản lý nội dung bài giảng',
    'admin.contentManagementDesc': 'Thêm, sửa, xóa video bài giảng và quiz',
    'admin.addNewLesson': 'Thêm bài mới',
    'admin.noLessonsAdmin': 'Chưa có bài giảng nào.',
    'admin.courseManagement': 'Quản lý khóa học',
    'admin.courseManagementDesc': 'Thêm và sửa khóa học',
    'admin.gradeManagement': 'Quản lý điểm',
    'admin.gradeManagementDesc': 'Xem điểm học sinh',
    'admin.studentView': 'Giao diện học sinh',
    'admin.beginner': 'Sơ cấp',
    'admin.intermediate': 'Trung cấp',
    'admin.advanced': 'Cao cấp',
    'admin.confirmRevoke': 'Bạn có chắc chắn muốn thu hồi quyền của học sinh này?',
    'admin.confirmGrant': 'Bạn có muốn cấp quyền học cho học sinh này?',
    'admin.updateFailed': 'Cập nhật quyền thất bại.',
    'admin.lesson': 'Bài giảng',
    'admin.edit': 'Sửa',
    'admin.viewAllStudents': 'Xem tất cả học sinh',

    // 코스 페이지
    'courses.title': 'Danh sách khóa học',
    'courses.subtitle': 'Nội dung giáo dục dành riêng cho du học sinh Việt Nam từ AJU E&J',
    'courses.waitingApproval': 'Đang chờ phê duyệt quyền học',
    'courses.waitingMessage': 'Đang chờ phê duyệt từ quản trị viên. Sau khi được phê duyệt, bạn có thể xem tất cả bài giảng.',
    'courses.contact': 'Liên hệ: admin@ajuenj.com',
    'courses.loadingCourses': 'Đang tải khóa học...',
    'courses.noCourses': 'Chưa có khóa học nào.',
    'courses.startCourse': 'Bắt đầu học',
    'courses.waitingStatus': 'Đang chờ phê duyệt',
    'courses.brandTitle': 'AJU E&J Education',
    'courses.brandDesc': 'Chương trình giáo dục tùy chỉnh cho cuộc sống thành công tại Hàn Quốc của du học sinh Việt Nam',
    'courses.feature1': 'Chương trình có hệ thống',
    'courses.feature2': 'Giáo dục thực hành',
    'courses.feature3': 'Học mọi lúc, mọi nơi',

    // 내 학습 진도
    'progress.title': 'Tình hình học tập',
    'progress.subtitle': 'Kiểm tra tình hình học tập của bạn',
    'progress.overall': 'Tiến độ tổng thể',
    'progress.completedLessons': 'Bài đã hoàn thành',
    'progress.totalLessons': 'Tổng số bài',
    'progress.quizAverage': 'Điểm quiz trung bình',
    'progress.recentActivity': 'Hoạt động học tập gần đây',
    'progress.noActivity': 'Chưa có lịch sử học tập.',
    'progress.startLearning': 'Hãy bắt đầu học ngay!',
    'progress.goToDashboard': 'Đến Dashboard',
    'progress.lessonCompleted': 'Hoàn thành bài học',
    'progress.quizScore': 'Điểm Quiz',
    'progress.submittedQuizzes': 'Quiz đã nộp',
    'progress.averageScore': 'Điểm trung bình',
    'progress.count': '',
    'progress.points': 'điểm',
    'progress.progressByCourse': 'Tiến độ theo khóa học',
    'progress.noCourses': 'Chưa có khóa học nào.',
    'progress.completed': 'hoàn thành',
    'progress.progressRate': 'Tỷ lệ tiến độ',
    'progress.recentQuizResults': 'Kết quả Quiz gần đây',
    'progress.noQuizzes': 'Chưa nộp quiz nào.',
    'progress.chapter': 'Chương',
    'progress.score': 'Điểm',
    'progress.submittedDate': 'Ngày nộp',
    'progress.unknown': 'Không rõ',

    // 프로필 설정
    'profile.title': 'Cài đặt hồ sơ',
    'profile.subtitle': 'Vui lòng nhập thông tin cần thiết cho việc học',
    'profile.name': 'Tên',
    'profile.namePlaceholder': 'Ví dụ: NGUYEN VAN A',
    'profile.zaloId': 'Zalo ID',
    'profile.zaloPlaceholder': 'Ví dụ: zalo123456',
    'profile.location': 'Nơi ở',
    'profile.locationPlaceholder': 'Khu vực hiện tại',
    'profile.level': 'Trình độ tiếng Hàn',
    'profile.selectLevel': 'Vui lòng chọn',
    'profile.saveProfile': 'Lưu hồ sơ',
    'profile.saving': 'Đang lưu...',
    'profile.welcome': 'Chào mừng!',
    'profile.welcomeMessage': 'Vui lòng cài đặt hồ sơ trước khi bắt đầu học',
    'profile.nameRequired': 'Tên là trường bắt buộc.',
    'profile.passportName': 'Tên hộ chiếu',
    'profile.optional': 'tùy chọn',
    'profile.zaloHelp': 'Bạn có thể nhận thông báo về việc học',
    'profile.startLearning': 'Bắt đầu học',
    'profile.skip': 'Bỏ qua',
    'profile.privacyNotice': 'Thông tin bạn nhập chỉ được sử dụng để cung cấp dịch vụ giáo dục AJU E&J',

    // 네비게이션
    'nav.dashboard': 'Dashboard',
    'nav.courses': 'Khóa học',
    'nav.myProgress': 'Tiến độ',
    'nav.myOrders': 'Đơn hàng',
    'nav.admin': 'Admin',

    // 학생 레이아웃
    'layout.menu': 'Menu',
    'layout.closeMenu': 'Đóng menu',

    // 챕터 관리
    'chapters.title': 'Quản lý Chương',
    'chapters.description': 'Thêm và quản lý các chương bài giảng',
    'chapters.addNew': 'Thêm chương mới',
    'chapters.editChapter': 'Sửa chương',
    'chapters.courseFilter': 'Lọc khóa học',
    'chapters.allCourses': 'Tất cả khóa học',
    'chapters.selectCourse': 'Chọn khóa học',
    'chapters.chapterTitle': 'Tiêu đề chương',
    'chapters.titlePlaceholder': 'Nhập tiêu đề chương',
    'chapters.youtubeUrl': 'URL YouTube',
    'chapters.youtubeHelp': 'Nhập link chia sẻ YouTube (ví dụ: https://youtu.be/...)',
    'chapters.sortOrder': 'Thứ tự sắp xếp',
    'chapters.videoDuration': 'Thời lượng video (phút)',
    'chapters.durationPlaceholder': 'phút',
    'chapters.quizSettings': 'Cài đặt Quiz',
    'chapters.optional': 'tùy chọn',
    'chapters.questions': ' câu hỏi',
    'chapters.question': 'Câu hỏi',
    'chapters.questionPlaceholder': 'Nhập câu hỏi',
    'chapters.option': 'Lựa chọn',
    'chapters.correct': 'Đáp án đúng',
    'chapters.incorrectOptions': 'Đáp án sai',
    'chapters.explanation': 'Giải thích',
    'chapters.explanationPlaceholder': 'Nhập giải thích (tùy chọn)',
    'chapters.removeQuestion': 'Xóa câu hỏi',
    'chapters.addQuestion': 'Thêm câu hỏi',
    'chapters.updated': 'Đã cập nhật chương.',
    'chapters.added': 'Đã thêm chương.',
    'chapters.confirmDelete': 'Bạn có chắc chắn muốn xóa chương này?',
    'chapters.deleted': 'Đã xóa chương.',
    'chapters.deleteFailed': 'Xóa chương thất bại.',
    'chapters.saveFailed': 'Lưu thất bại.',
    'chapters.chaptersCount': ' chương',
    'chapters.order': 'Thứ tự',
    'chapters.chapterInfo': 'Thông tin chương',
    'chapters.course': 'Khóa học',
    'chapters.quiz': 'Quiz',
    'chapters.actions': 'Hành động',
    'chapters.noChapters': 'Chưa có chương nào.',
    'chapters.minutes': 'phút',
    'chapters.noTime': 'Không có thời gian',
    'chapters.noCourse': 'Không có khóa học',
    'chapters.none': 'Không có',
    'chapters.helpGuide': 'Hướng dẫn quản lý chương',
    'chapters.helpTip1': 'Nhập URL YouTube dạng link chia sẻ',
    'chapters.helpTip2': 'Thứ tự sắp xếp nhỏ hơn sẽ hiển thị trước',
    'chapters.helpTip3': 'Quiz là tùy chọn, dùng để kiểm tra học tập',
    'chapters.helpTip4': 'Khi xóa chương, kết quả quiz liên quan cũng sẽ bị xóa',

    // 코스 관리
    'courses.managementTitle': 'Quản lý Khóa học',
    'courses.managementDesc': 'Thêm và quản lý các khóa học',
    'courses.addNew': 'Thêm khóa học mới',
    'courses.editCourse': 'Sửa khóa học',
    'courses.courseTitle': 'Tiêu đề khóa học',
    'courses.titlePlaceholder': 'Nhập tiêu đề khóa học',
    'courses.courseDescription': 'Mô tả khóa học',
    'courses.descriptionPlaceholder': 'Nhập mô tả khóa học',
    'courses.thumbnailUrl': 'URL Thumbnail',
    'courses.sortOrder': 'Thứ tự sắp xếp',
    'courses.activeStatus': 'Trạng thái hoạt động',
    'courses.active': 'Hoạt động',
    'courses.inactive': 'Không hoạt động',
    'courses.add': 'Thêm',
    'courses.courseUpdated': 'Đã cập nhật khóa học.',
    'courses.courseAdded': 'Đã thêm khóa học.',
    'courses.saveFailed': 'Lưu thất bại.',
    'courses.confirmDelete': 'Bạn có chắc chắn muốn xóa khóa học này?',
    'courses.courseDeleted': 'Đã xóa khóa học.',
    'courses.deleteFailed': 'Xóa khóa học thất bại.',
    'courses.coursesCount': ' khóa học',
    'courses.order': 'Thứ tự',
    'courses.courseInfo': 'Thông tin khóa học',

    // 성적 관리
    'grades.title': 'Quản lý Điểm',
    'grades.description': 'Xem điểm quiz của học sinh',
    'grades.courseFilter': 'Lọc khóa học',
    'grades.allCourses': 'Tất cả khóa học',
    'grades.totalStudents': 'Tổng học sinh',
    'grades.submittedQuizzes': 'Quiz đã nộp',
    'grades.overallAverage': 'Trung bình chung',
    'grades.highestScore': 'Điểm cao nhất',
    'grades.studentGrades': 'Điểm theo học sinh',
    'grades.rank': 'Xếp hạng',
    'grades.studentInfo': 'Thông tin học sinh',
    'grades.submissions': 'Số lần nộp',
    'grades.averageScore': 'Điểm trung bình',
    'grades.noData': 'Không có dữ liệu.',
    'grades.submissionsCount': '',
    'grades.points': ' điểm',
    'grades.excellent': 'Xuất sắc',
    'grades.average': 'Trung bình',
    'grades.needsWork': 'Cần cố gắng',
    'grades.chapterQuizStats': 'Tỷ lệ đúng Quiz theo chương',
    'grades.takers': ' người thi',

    // 학생 관리
    'students.title': 'Quản lý Học sinh',
    'students.description': 'Xác nhận thanh toán và phê duyệt quyền học của học sinh',
    'students.total': 'Tổng',
    'students.pending': 'Đang chờ',
    'students.approved': 'Đã duyệt',
    'students.studentInfo': 'Thông tin học sinh',
    'students.contact': 'Liên hệ',
    'students.locationLevel': 'Khu vực/Trình độ',
    'students.joinDate': 'Ngày đăng ký',
    'students.noStudents': 'Không có học sinh',
    'students.notRegistered': 'Chưa đăng ký',
    'students.notSet': 'Chưa cài đặt',
    'students.beginner': 'Sơ cấp',
    'students.intermediate': 'Trung cấp',
    'students.advanced': 'Cao cấp',
    'students.revoke': 'Thu hồi',
    'students.approve': 'Phê duyệt',
    'students.confirmRevoke': 'Bạn có chắc chắn muốn thu hồi quyền của học sinh này?',
    'students.confirmApprove': 'Bạn có muốn cấp quyền học cho học sinh này?',
    'students.approvalRevoked': 'Đã thu hồi quyền',
    'students.approvalError': 'Đã xảy ra lỗi khi xử lý phê duyệt.',
    'students.approvalGuide': 'Hướng dẫn phê duyệt',
    'students.guideTip1': 'Kiểm tra Zalo ID để xác nhận học sinh thực sự',
    'students.guideTip2': 'Chỉ nhấn phê duyệt khi đã xác nhận thanh toán',
    'students.guideTip3': 'Chỉ học sinh được phê duyệt mới có thể truy cập nội dung bài giảng',
    'students.searchPlaceholder': 'Tìm theo tên hoặc email...',

    // 관리자 네비게이션
    'adminNav.adminPanel': 'Bảng quản trị',
    'adminNav.navigation': 'Menu',
    'adminNav.dashboard': 'Bảng điều khiển',
    'adminNav.dashboardSub': 'Tổng quan',
    'adminNav.orders': 'Quản lý đơn hàng & vận chuyển',
    'adminNav.ordersSub': 'Đơn hàng/Giao hàng',
    'adminNav.students': 'Quản lý Học sinh',
    'adminNav.studentsSub': 'Học sinh',
    'adminNav.courses': 'Quản lý Khóa học',
    'adminNav.coursesSub': 'Khóa học',
    'adminNav.chaptersSimple': 'Quản lý Chương (Đơn giản)',
    'adminNav.chaptersSub': 'Chương',
    'adminNav.chaptersDetail': 'Quản lý Chương (Chi tiết)',
    'adminNav.chaptersDetailSub': 'Chi tiết chương',
    'adminNav.grades': 'Xem Điểm',
    'adminNav.gradesSub': 'Điểm số',
    'adminNav.studentView': 'Giao diện Học sinh',

    // 구독 관리
    'subscription.status': 'Trạng thái đăng ký',
    'subscription.period': 'Thời hạn đăng ký',
    'subscription.active': 'Đang hoạt động',
    'subscription.expired': 'Đã hết hạn',
    'subscription.unlimited': 'Không giới hạn',
    'subscription.approve': 'Phê duyệt',
    'subscription.extend': 'Gia hạn',
    'subscription.renew': 'Đăng ký lại',
    'subscription.revoke': 'Thu hồi',
    'subscription.approved': '✅ Đã phê duyệt đăng ký.',
    'subscription.extended': '✅ Đã gia hạn đăng ký.',
    'subscription.error': 'Đã xảy ra lỗi khi xử lý đăng ký.',
    'subscription.approveTitle': 'Phê duyệt đăng ký',
    'subscription.extendTitle': 'Gia hạn đăng ký',
    'subscription.selectPeriod': 'Chọn thời hạn đăng ký',
    'subscription.customInput': 'Nhập trực tiếp',
    'subscription.month': 'tháng',
    'subscription.months': 'tháng',
    'subscription.monthPlan': ' tháng',
    'subscription.currentExpiry': 'Ngày hết hạn hiện tại',
    'subscription.newExpiry': 'Ngày hết hạn sau gia hạn',
    'subscription.expiryDate': 'Ngày hết hạn dự kiến',
    'subscription.daysRemaining': 'Còn {days} ngày',
    'subscription.until': 'đến',
    'subscription.expiredMessage': 'Thời hạn đăng ký đã hết. Vui lòng gia hạn để tiếp tục học.',
    'subscription.expiringMessage': 'Đăng ký sẽ hết hạn sau {days} ngày. Vui lòng liên hệ Zalo để gia hạn.',
    'subscription.guide': 'Hướng dẫn quản lý đăng ký',
    'subscription.guideTip1': 'Có thể đặt thời hạn đăng ký theo 1, 3, 6, 12 tháng',
    'subscription.guideTip2': 'Khi gia hạn, thời gian được cộng thêm từ ngày hết hạn (nếu đã hết hạn thì từ hôm nay)',
    'subscription.guideTip3': 'Hiển thị màu đỏ khi còn 7 ngày trước khi hết hạn',
    'subscription.guideTip4': 'Học sinh hết hạn sẽ tự động bị chặn truy cập bài giảng',

    // 챕터 관리 V2 (간편 모드)
    'chaptersV2.title': 'Quản lý Chương (Chế độ đơn giản)',
    'chaptersV2.description': 'Thêm và quản lý chương theo khóa học một cách đơn giản',
    'chaptersV2.step1Title': 'Chọn Khóa học (Thư mục giáo trình)',
    'chaptersV2.noCourses': 'Chưa có khóa học nào.',
    'chaptersV2.goAddCourse': 'Đi đến thêm khóa học →',
    'chaptersV2.chaptersCount': ' chương',
    'chaptersV2.chapterList': 'Danh sách chương',
    'chaptersV2.addChapter': 'Thêm chương',
    'chaptersV2.noChaptersYet': 'Chưa có chương nào',
    'chaptersV2.clickAddChapter': 'Nhấn nút "Thêm chương" ở trên',
    'chaptersV2.quizQuestions': '{count} câu quiz',
    'chaptersV2.editChapter': 'Sửa chương',
    'chaptersV2.addNewChapter': 'Thêm chương mới',
    'chaptersV2.chapterTitle': 'Tiêu đề chương',
    'chaptersV2.titlePlaceholder': 'Ví dụ: Bài 1 - Tiếng Hàn cơ bản',
    'chaptersV2.youtubeUrl': 'URL YouTube',
    'chaptersV2.youtubeHelp': 'Nhập URL video YouTube',
    'chaptersV2.order': 'Thứ tự',
    'chaptersV2.videoDuration': 'Thời lượng video (phút)',
    'chaptersV2.quizOptional': 'Quiz (Tùy chọn)',
    'chaptersV2.addQuestion': 'Thêm câu hỏi',
    'chaptersV2.question': 'Câu hỏi',
    'chaptersV2.option': 'Lựa chọn',
    'chaptersV2.deleteQuestion': 'Xóa câu hỏi',
    'chaptersV2.update': 'Cập nhật',
    'chaptersV2.add': 'Thêm',
    'chaptersV2.helpTitle': '💡 Hướng dẫn sử dụng',
    'chaptersV2.helpTip1': 'Đầu tiên hãy chọn khóa học',
    'chaptersV2.helpTip2': 'Tiêu đề chương và URL YouTube là bắt buộc',
    'chaptersV2.helpTip3': 'Quiz là tùy chọn',
    'chaptersV2.helpTip4': 'Số thứ tự nhỏ hơn sẽ hiển thị trước',
    'chaptersV2.selectCourseAlert': 'Vui lòng chọn khóa học.',
    'chaptersV2.requiredFieldsAlert': 'Tiêu đề chương và URL YouTube là bắt buộc.',
    'chaptersV2.chapterUpdated': '✅ Đã cập nhật chương.',
    'chaptersV2.chapterAdded': '✅ Đã thêm chương.',
    'chaptersV2.saveError': 'Đã xảy ra lỗi khi lưu.',
    'chaptersV2.chapterDeleted': '✅ Đã xóa chương.',
    'chaptersV2.deleteError': 'Đã xảy ra lỗi khi xóa.',

    // 알림
    'notification.title': 'Thông báo',
    'notification.markAllRead': 'Đánh dấu đã đọc',
    'notification.loading': 'Đang tải...',
    'notification.noNotifications': 'Không có thông báo',
    'notification.justNow': 'Vừa xong',
    'notification.minutesAgo': '{n} phút trước',
    'notification.hoursAgo': '{n} giờ trước',
    'notification.daysAgo': '{n} ngày trước',
    'notification.showingRecent': 'Hiển thị {n} thông báo gần đây nhất',

    // 주문 내역
    'orders.title': 'Lịch sử đơn hàng',
    'orders.subtitle': 'Kiểm tra lịch sử đăng ký và thanh toán khóa học',
    'orders.noOrders': 'Không có đơn hàng nào',
    'orders.goEnroll': 'Xem khóa học',
    'orders.orderDate': 'Ngày đặt',
    'orders.orderId': 'Mã đơn hàng',
    'orders.courseName': 'Tên khóa học',
    'orders.period': 'Thời hạn học',
    'orders.months': 'tháng',
    'orders.amount': 'Số tiền',
    'orders.courseAmount': 'Tiền khóa học',
    'orders.textbookAmount': 'Tiền giáo trình',
    'orders.totalAmount': 'Tổng thanh toán',
    'orders.status': 'Trạng thái',
    'orders.pendingPayment': 'Chờ thanh toán',
    'orders.paid': 'Đã thanh toán',
    'orders.cancelled': 'Đã hủy',
    'orders.depositInfo': 'Thông tin chuyển khoản',
    'orders.bankName': 'Ngân hàng',
    'orders.accountNumber': 'Số tài khoản',
    'orders.accountHolder': 'Chủ tài khoản',
    'orders.copyAccount': 'Sao chép',
    'orders.copied': 'Đã sao chép!',
    'orders.confirmDeposit': 'Thông báo đã chuyển khoản',
    'orders.depositConfirmed': 'Đã gửi yêu cầu xác nhận',
    'orders.waitingConfirm': 'Đang chờ xác nhận',
    'orders.deliveryInfo': 'Thông tin giao hàng',
    'orders.deliveryStatus': 'Trạng thái giao hàng',
    'orders.trackingNumber': 'Mã vận đơn',
    'orders.carrier': 'Đơn vị vận chuyển',
    'orders.preparing': 'Đang chuẩn bị',
    'orders.shipped': 'Đang giao',
    'orders.delivered': 'Đã giao',
    'orders.trackDelivery': 'Theo dõi giao hàng',
    'orders.shippingAddress': 'Địa chỉ giao hàng',
    'orders.recipient': 'Người nhận',
    'orders.phone': 'Số điện thoại',
    'orders.address': 'Địa chỉ',
    'orders.textbook': 'Giáo trình',
    'orders.included': 'Có',
    'orders.notIncluded': 'Không',
    'orders.won': 'won',
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('vi'); // 기본 언어: 베트남어

  // localStorage에서 언어 설정 불러오기
  useEffect(() => {
    if (typeof window !== 'undefined') {
      const savedLanguage = localStorage.getItem('aju_lang_v2') as Language;
      if (savedLanguage && (savedLanguage === 'ko' || savedLanguage === 'vi')) {
        setLanguage(savedLanguage);
      }
    }
  }, []);

  // 언어 전환
  const toggleLanguage = () => {
    const newLanguage = language === 'ko' ? 'vi' : 'ko';
    setLanguage(newLanguage);
    if (typeof window !== 'undefined') {
      localStorage.setItem('aju_lang_v2', newLanguage);
    }
  };

  // 번역 함수
  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}
